version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8020:8020"
    depends_on:
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: graph
      postgres_pass: "{{password}}"
      postgres_db: graph
      GRAPH_LOG: info
      ipfs: "https://ipfs.snowapi.net/"
      ethereum: "avalanche:https://api.avax.network/ext/bc/C/rpc"
      ETHEREUM_POLLING_INTERVAL: 1000
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "graph"
      POSTGRES_PASSWORD: "{{password}}"
      POSTGRES_DB: "graph"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data